### ISSUE TITLE
Error when I'm trying to build the project - Rust

### ISSUE THREAD

**Issue by Victor1890** [frectonz/sql-studio#39]
**Describe the bug**
When I run **cargo build** but this library libduckdb-sys v0.10.2 return one strange error

**To Reproduce**
1. Clone the project and I go inside project
2. Run **cargo build**

**Screenshots**
![image](https://github.com/user-attachments/assets/1a3f4e16-0259-4ad8-8c4d-51935f371712)

**Desktop (please complete the following information):**
 - OS: Windows 11 WSL (Ubuntu)
-  Browser N/A
 - Version: Rust 1.75.0 (82e1608df 2023-12-21)

**Comment by frectonz** [comment]
Since some of the DB drivers this project depends on are compiled from source on build. We expect you to have a c compiler (`gcc`) installed on your machine. 

Since we value reproducibility and build time issues can be caused a lot of different issues like version mismatch etc, we generally recommend using nix to build the project.
